### ISSUE TITLE
Parse Liquid output within asset_source tag

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll-assets#183]
_This is new functionality, not currently available in v1 of the plugin._

When using the `{% asset_source %}` tag, it should parse Liquid markup before processing. For example:

```
{% if page.featured %}
    {% asset_source logo--{{ page.title | slugify }}.svg %}
{% else %}
    {{ page.title }}
{% endif %}
```

(The parsing of output markup across all tags provided by this plugin may be desirable also.)

**Comment by envygeeks** [comment]
Hulk: +backlog/jekyll +discover:tag.rb++context +v2.1

**Comment by envygeeks** [comment]
Hulk is here, you have access to "context" through https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/tag.rb#L45, it is not available elsewhere.  This is a problem.

**Comment by envygeeks** [comment]
Looks like I'll need to start passing around context, this is definitely a 2.1 change because that's a lot of effort and we are trying to keep from major internal changes while I wait for @parkr to decide when 3.0.0 is due the last thing I want is to release late.

**Comment by parkr** [comment]
Oct 26 for Jekyll 3 final. Will release RC1 this week.

**Comment by paulrobertlloyd** [comment]
Thanks for taking a look at this for v2.0. Just tried the markup (or similar) I provided in this issue, and got the following error:

``Liquid Exception: Liquid syntax error: Variable '{{' was not properly terminated with regexp: /\}\}/ in _includes/item/project.html, included in projects/index.html``

This is the relevant part of the template (regardless what variable I provide, I get the same error):

```html
{% asset_source {{ item.title }} %}
```

Here’s the trace:
```
  Liquid Exception: Liquid syntax error: Variable '{{' was not properly terminated with regexp: /\}\}/ in _includes/item/project.html, included in projects/index.html
/Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/tags/include.rb:133:in `rescue in render': Liquid syntax error: Variable '{{' was not properly terminated with regexp: /\}\}/ (Jekyll::Tags::IncludeTagError)
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/tags/include.rb:125:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/if.rb:39:in `block (2 levels) in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/if.rb:37:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/if.rb:37:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/context.rb:132:in `stack'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/if.rb:36:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/for.rb:113:in `block (2 levels) in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/for.rb:100:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/for.rb:100:in `each_with_index'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/for.rb:100:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/context.rb:132:in `stack'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/for.rb:99:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/liquid_renderer/file.rb:36:in `measure_bytes'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/convertible.rb:112:in `render_liquid'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/convertible.rb:255:in `do_layout'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/page.rb:116:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/site.rb:179:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/site.rb:177:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/site.rb:177:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/site.rb:59:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/command.rb:28:in `process_site'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/commands/build.rb:60:in `build'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/commands/build.rb:35:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bundler/gems/jekyll-03d3eb7191a6/bin/jekyll:17:in `<top (required)>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `load'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `<main>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

What I’m attempting *should* work, correct?

**Comment by envygeeks** [comment]
@paulrobertlloyd you need to quote it because we parse the same way a Ruby would ARGV which means {{ var }} will end up as ['{{', 'var', '}}'], so you need to do

```
{% img "{{ var }}" %}
{% img img.jpg proxy:key:"{{ var }}" %}
{% img img.jpg "proxy:key:{{ var }}" %}

**Comment by envygeeks** [comment]
You can also escape the spaces too just like you can a terminal:

```
{% img {{\ var\ }}
```

**Comment by paulrobertlloyd** [comment]
Ah, that makes sense. Thanks for the info — tried this, and it worked. Fantastic!

**Comment by paulrobertlloyd** [comment]
Sorry to go round in circles on this one but… this isn’t working again. It was, then the liquid caching stuff landed, and it’s broken again. I know you addressed this in https://github.com/jekyll/jekyll-assets/commit/1eb580f9b183728c503f4675280428583165c23b, but that change doesn’t seem to have fixed this issue, sadly.

Here’s my template as it stands now:

```html
{% if item.featured %}
    {% capture item_logo %}c-item__logo--{{ item.title | slugify }}.svg{% endcapture %}
    {% asset_source "{{ item_logo }}" %}
{% else %}
    {{ item.title }}
{% endif %}
```

here is the error:

```
Liquid Exception: Could not find the asset `{{ item_logo }}' in _includes/item/project.html, included in projects/index.html
```

and here is the full trace:

```
  Liquid Exception: Could not find the asset `{{ item_logo }}' in _includes/item/project.html, included in projects/index.html
/Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/tags/include.rb:133:in `rescue in render': Could not find the asset `{{ item_logo }}' (Jekyll::Tags::IncludeTagError)
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/tags/include.rb:125:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/if.rb:39:in `block (2 levels) in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/if.rb:37:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/if.rb:37:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/context.rb:132:in `stack'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/if.rb:36:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/for.rb:113:in `block (2 levels) in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/for.rb:100:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/for.rb:100:in `each_with_index'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/for.rb:100:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/context.rb:132:in `stack'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/for.rb:99:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:36:in `measure_bytes'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/convertible.rb:112:in `render_liquid'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/convertible.rb:255:in `do_layout'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/page.rb:116:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/site.rb:179:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/site.rb:177:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/site.rb:177:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/site.rb:59:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/command.rb:28:in `process_site'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:60:in `build'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:35:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `load'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `<main>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

Any ideas!?

**Comment by envygeeks** [comment]
I have no idea what is going on but I do know if you want me to look at it on Monday you'll need to file this into a new ticket or I'll completely forget about it since I don't track closed tickets.

**Comment by paulrobertlloyd** [comment]
Done (and thanks)!
