### ISSUE TITLE
2.0 beta1 - Unknown tag 'stylesheet'

### ISSUE THREAD

**Issue by jrodrigosm** [jekyll/jekyll-assets#186]
Hi,

I'm testing the migration from jekyll2/jekyll-assets1 to jekyll3/jekyll-assets2 (beta10 and beta1, respectively).

I must be doing something wrong, because when trying to serve the site in development with `jekyll serve` I get

```
  Liquid Exception: Liquid syntax error: Unknown tag 'stylesheet' in _layouts/home.html
/home/x/.rvm/gems/ruby-2.2.2/gems/liquid-3.0.6/lib/liquid/block.rb:87:in `unknown_tag': Liquid syntax error: Unknown tag 'stylesheet' (Liquid::SyntaxError)
	from /home/x/.rvm/gems/ruby-2.2.2/gems/liquid-3.0.6/lib/liquid/block.rb:38:in `parse'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/liquid-3.0.6/lib/liquid/tag.rb:10:in `parse'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/liquid-3.0.6/lib/liquid/document.rb:5:in `parse'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/liquid-3.0.6/lib/liquid/template.rb:122:in `parse'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/liquid-3.0.6/lib/liquid/template.rb:108:in `parse'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/jekyll-3.0.0.pre.beta10/lib/jekyll/liquid_renderer/file.rb:11:in `block in parse'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/jekyll-3.0.0.pre.beta10/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/jekyll-3.0.0.pre.beta10/lib/jekyll/liquid_renderer/file.rb:10:in `parse'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/jekyll-3.0.0.pre.beta10/lib/jekyll/convertible.rb:112:in `render_liquid'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/jekyll-3.0.0.pre.beta10/lib/jekyll/convertible.rb:220:in `render_all_layouts'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/jekyll-3.0.0.pre.beta10/lib/jekyll/convertible.rb:261:in `do_layout'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/jekyll-3.0.0.pre.beta10/lib/jekyll/page.rb:116:in `render'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/jekyll-3.0.0.pre.beta10/lib/jekyll/site.rb:180:in `block in render'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/jekyll-3.0.0.pre.beta10/lib/jekyll/site.rb:178:in `each'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/jekyll-3.0.0.pre.beta10/lib/jekyll/site.rb:178:in `render'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/jekyll-3.0.0.pre.beta10/lib/jekyll/site.rb:59:in `process'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/jekyll-3.0.0.pre.beta10/lib/jekyll/command.rb:28:in `process_site'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/jekyll-3.0.0.pre.beta10/lib/jekyll/commands/build.rb:60:in `build'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/jekyll-3.0.0.pre.beta10/lib/jekyll/commands/build.rb:35:in `process'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/jekyll-3.0.0.pre.beta10/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /home/x/.rvm/gems/ruby-2.2.2/gems/jekyll-3.0.0.pre.beta10/bin/jekyll:17:in `<top (required)>'
	from /home/x/.rvm/gems/ruby-2.2.2/bin/jekyll:23:in `load'
	from /home/x/.rvm/gems/ruby-2.2.2/bin/jekyll:23:in `<main>'
	from /home/x/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/x/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

For some reason, Jekyll is not using jekyll-assets. I am assuming that my mistake must be related to not configuring jekyll-assets correctly.

Here's my _config.yml (which I did not change from the previous version):

    baseurl: ""
    markdown: kramdown
    permalink: pretty
    assets:
      js_compressor:  uglifier
      css_compressor: sass
      sources:
        - _assets/images
        - _assets/javascripts
        - _assets/stylesheets
        - _assets/fonts

Any thoughts? Thanks!

**Comment by envygeeks** [comment]
You are using global gems through RVM so you will need to use `gems` in `_config.yml` as I just added to the README.me:  https://github.com/jekyll/jekyll-assets#using-jekyll-assets-with-jekyll

**Comment by jrodrigosm** [comment]
Mmm ... sorry for not being explicit enough, I did not install Jekyll as a global gem, but through bundler. I'm actually launching jekyll with `bundle exec jekyll serve --trace`, and I get the error message that I paste above. Bundler is not picking up jekyll-assets despite launching jekyll with `bundle exec`.

If I follow your suggestion and add
```
gems:
  - jekyll-assets
```
to my _config.yml, launching jekyll with `bundle exec jekyll serve --trace` then I get a different error:
```
/home/x/.rvm/gems/ruby-2.2.2/gems/jekyll-3.0.0.pre.beta10/lib/jekyll/plugin_manager.rb:30:in `require': cannot load such file -- jekyll-assets (LoadError)
```

For your info, this is my Gemfile:
```
source 'https://rubygems.org'

gem 'jekyll', '3.0.0.pre.beta10'
gem 'jekyll-assets', '2.0.0.pre.beta1'
```
and this is my Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    colorator (0.1)
    ffi (1.9.10)
    jekyll (3.0.0.pre.beta10)
      colorator (~> 0.1)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 3.0)
      mercenary (~> 0.3.3)
      rouge (~> 1.7)
      safe_yaml (~> 1.0)
    jekyll-assets (2.0.0.pre.beta1)
      jekyll (~> 3.0.0.pre.beta9)
      sprockets (~> 3.3)
      sprockets-helpers (~> 1.2)
    jekyll-sass-converter (1.3.0)
      sass (~> 3.2)
    jekyll-watch (1.3.0)
      listen (~> 3.0)
    kramdown (1.9.0)
    liquid (3.0.6)
    listen (3.0.3)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    mercenary (0.3.5)
    rack (1.6.4)
    rb-fsevent (0.9.6)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    rouge (1.10.1)
    safe_yaml (1.0.4)
    sass (3.4.19)
    sprockets (3.4.0)
      rack (> 1, < 3)
    sprockets-helpers (1.2.1)
      sprockets (>= 2.2)

PLATFORMS
  ruby

DEPENDENCIES
  jekyll (= 3.0.0.pre.beta10)
  jekyll-assets (= 2.0.0.pre.beta1)

BUNDLED WITH
   1.10.6
```

**Comment by jrodrigosm** [comment]
It works with beta2. Thanks.

**Comment by envygeeks** [comment]
It was probably because we re-added the jekyll-assets file after it was noticed Official docs for Jekyll use `jekyll-assets` and I wanted to avoid having to adjust the docs.  Glad it works now!

**Comment by liuzxc** [comment]
it works for me! Thanks @jrodrigosm
