### ISSUE TITLE
Liquid output not parsed in asset_source tag

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll-assets#211]
Sorry to go round in circles on this one but… [this](https://github.com/jekyll/jekyll-assets/issues/183) isn’t working again. It was, then the [liquid caching stuff landed](https://github.com/jekyll/jekyll/issues/4120), and it’s broken again. I know you addressed this in https://github.com/jekyll/jekyll-assets/commit/1eb580f9b183728c503f4675280428583165c23b, but that change doesn’t seem to have fixed this issue, sadly.

Here’s my template as it stands now:

```html
{% if item.featured %}
    {% capture item_logo %}c-item__logo--{{ item.title | slugify }}.svg{% endcapture %}
    {% asset_source "{{ item_logo }}" %}
{% else %}
    {{ item.title }}
{% endif %}
```

here is the error:

```
Liquid Exception: Could not find the asset `{{ item_logo }}' in _includes/item/project.html, included in projects/index.html
```

and here is the full trace:

```
  Liquid Exception: Could not find the asset `{{ item_logo }}' in _includes/item/project.html, included in projects/index.html
/Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/tags/include.rb:133:in `rescue in render': Could not find the asset `{{ item_logo }}' (Jekyll::Tags::IncludeTagError)
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/tags/include.rb:125:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/if.rb:39:in `block (2 levels) in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/if.rb:37:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/if.rb:37:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/context.rb:132:in `stack'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/if.rb:36:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/for.rb:113:in `block (2 levels) in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/for.rb:100:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/for.rb:100:in `each_with_index'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/for.rb:100:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/context.rb:132:in `stack'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tags/for.rb:99:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:36:in `measure_bytes'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/convertible.rb:112:in `render_liquid'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/convertible.rb:255:in `do_layout'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/page.rb:116:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/site.rb:179:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/site.rb:177:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/site.rb:177:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/site.rb:59:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/command.rb:28:in `process_site'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:60:in `build'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:35:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `load'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `<main>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

Any ideas!?

**Comment by envygeeks** [comment]
Hulk: remind me to add a note in the documentation that Liquid rendering is experimental.

I'm going to look at this Monday but if I'm honest, this might not be a bug with us.  I can't explain why this would happen since we use the context that is given to us and if it's not in the context I can't magically make it appear.  I can't explain why this would happen but what I will do is test multiple ways.

**Comment by lekkerduidelijk** [comment]
I'm experiencing a similar same issue with ``asset_path``.

My template:
```
{% capture work_bg %}work/{{ page.title | slugify }}/bg.jpg{% endcapture %}
<header style="background-image:url({% asset_path "{{ work_bg }}" %} );">
```

The error:
```
Liquid Exception: Could not find the asset `{{ work_bg }}' in _layouts/work.html
jekyll 3.0.1 | Error:  Could not find the asset `{{ work_bg }}'
```

Full trace:
```
  Liquid Exception: Could not find the asset `{{ work_bg }}' in _layouts/work.html
/Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-assets-2.0.3/lib/jekyll/assets/liquid/tag.rb:154:in `find_asset': Could not find the asset `{{ work_bg }}' (Jekyll::Assets::Liquid::Tag::AssetNotFoundError)
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-assets-2.0.3/lib/jekyll/assets/liquid/tag.rb:83:in `render'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:36:in `measure_bytes'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/renderer.rb:105:in `render_liquid'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/renderer.rb:147:in `place_in_layouts'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/renderer.rb:69:in `run'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:171:in `block (2 levels) in render'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:169:in `each'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:169:in `block in render'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:168:in `each'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:168:in `render'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:59:in `process'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/command.rb:28:in `process_site'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:60:in `build'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:35:in `process'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/rutger/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
	from /Users/rutger/.rbenv/versions/2.1.5/bin/jekyll:23:in `load'
	from /Users/rutger/.rbenv/versions/2.1.5/bin/jekyll:23:in `<main>'
```

Maybe I'm missing something?

**Comment by envygeeks** [comment]
Your error is no different than the reported error and this ticket is still open, please remain calm as this is a low-priority bug out of all my projects because you can do it without the need of a capture.

**Comment by envygeeks** [comment]
For your case though @lekkerduidelijk try using 2.1-dev from HEAD (master), since we process assets with Liquid in dev now, that would probably suite you better for your case.

**Comment by lekkerduidelijk** [comment]
Thanks @envygeeks! No rush for me, just reporting :+1: 
Will try 2.1-dev.

**Comment by underyx** [comment]
I think I have a related issue.

My `default.html` layout has this bit:

```
    {% for path in page.js %}
      {% js '{{ path }}' %}
    {% endfor %}
```

And a random page has this in front matter:

```
layout: default
js:
  - profiles.js
```

The output of `jekyll build` is:

```
      Generating...
                    Could not find the asset `{{ path }}'
  Liquid Exception: Could not find the asset `{{ path }}' in _layouts/default.html
```

I'm getting this with jekyll-assets at 87034c98b9209059f4163605ce4742884d6d659a and jekyll 3.0.1.

**Comment by SeiferTim** [comment]
I thought I would point out that I'm having the same problem:
`{% img "{{ p.logo }}" %}` = `Could not find the asset '{{ p.logo }}'`

However: this DOES work:
`{% img path_to_my_img alt:"{{ p.logo }}" %}` = the alt tag shows the correct value of `p.logo`

Hopefully, this can help you solve the issue...

**Comment by SeiferTim** [comment]
So, I did some digging, and, I have very, very limited experience with ruby, but I think I found the problem...

In `tag.rb`, you're parsing the liquid for all arguments: https://github.com/jekyll/jekyll-assets/blob/1e8643b9039bdb886a759ef730e41a7668e424a5/lib/jekyll/assets/liquid/tag.rb#L77
...and setting it to the variable `args`.

Then, you call `find_asset`: https://github.com/jekyll/jekyll-assets/blob/1e8643b9039bdb886a759ef730e41a7668e424a5/lib/jekyll/assets/liquid/tag.rb#L83

BUT, you're using the `@args` variable in that function, which seems to be the pre-parsed version.
https://github.com/jekyll/jekyll-assets/blob/1e8643b9039bdb886a759ef730e41a7668e424a5/lib/jekyll/assets/liquid/tag.rb#L152

I was able to fix the problem by simply sticking: `@args[:file] = args[:file];` in right before calling `find_asset` - which _works_ but is almost certainly not the 'correct' solution.

Hope it helps!!

**Comment by envygeeks** [comment]
Well spotted. I agree it's nto the correct solution.  Liquid doesn't fire like a shotgun which is what led to all this looping issue and switching to args instead of @args and non-desctructive writing that led to the case you discovered (which probably is the problem...)

**Comment by envygeeks** [comment]
I hate to say this but this fix will not be going into 2.0, it's going into 2.1 because I had to change the API to implement this fix  efficiently and I'd rather suffer hatred over an API incompatible 2.1 than changing the API in a released version.

**Comment by underyx** [comment]
Awesome, thanks for the fix! :tada:

As a refresher for anyone who wants to use the fix right away, you should be able to specify the dependency in your `Gemfile` like this:

    gem 'jekyll-assets', :git => 'https://github.com/jekyll/jekyll-assets.git', :ref => 'a220643'

**Comment by envygeeks** [comment]
There probably won't be a need for that because once I implement CodeClimate Platform and cleanup the source I plan to handle one last ticket and release, which should happen within a few hours unless my source is that bad, which I wouldn't be surprised if it is because recently I discovered just how inconsistent I am with my own coding style on another project.

**Comment by paulrobertlloyd** [comment]
Just tested this fix (using the `Gemfile` specification above, just to test), and can confirm this is now fixed. Thanks @envygeeks for the fix, and @underyx for spotting the source of the issue.

**Comment by underyx** [comment]
I'll just go ahead and forward your misdirected appreciation to @SeiferTim.

Thanks, @SeiferTim!

**Comment by paulrobertlloyd** [comment]
@underyx Oh crap! I only looked so far up the page… yes, I mean thanks @SeiferTim!
