### ISSUE TITLE
Error possibly caused by Jekyll Assets when booting.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll-assets#216]
```
/srv/jekyll/vendor/bundle/ruby/2.2.0/bundler/gems/jekyll-fdf12efde40c/lib/jekyll/cleaner.rb:43:in `existing_files': undefined method `safe_glob' for Jekyll::Utils:Module (NoMethodError)
        from /srv/jekyll/vendor/bundle/ruby/2.2.0/bundler/gems/jekyll-fdf12efde40c/lib/jekyll/cleaner.rb:25:in `obsolete_files'
        from /srv/jekyll/vendor/bundle/ruby/2.2.0/bundler/gems/jekyll-assets-87034c98b920/lib/jekyll/assets/patches/jekyll/cleaner.rb:10:in `obsolete_files'
        from /srv/jekyll/vendor/bundle/ruby/2.2.0/bundler/gems/jekyll-fdf12efde40c/lib/jekyll/cleaner.rb:15:in `cleanup!'
        from /srv/jekyll/vendor/bundle/ruby/2.2.0/bundler/gems/jekyll-fdf12efde40c/lib/jekyll/site.rb:192:in `cleanup'
        from /srv/jekyll/vendor/bundle/ruby/2.2.0/bundler/gems/jekyll-fdf12efde40c/lib/jekyll/site.rb:60:in `process'
        from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/command.rb:28:in `process_site'
        from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:60:in `build'
        from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:35:in `process'
        from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<main>'
```

**Comment by envygeeks** [comment]
This is an upstream bug, our source doesn't even try to tap that method.
