### ISSUE TITLE
Unknown tag error (possible conflict with jekyll-archives)

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll-assets#219]
I’m getting the following error: `Liquid Exception: Liquid syntax error: Unknown tag 'asset_path' in _layouts/default.html`, where the “unknown tag” being whichever is the first to be parsed.

Here’s the trace:

```
/Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:87:in `unknown_tag': Liquid syntax error: Unknown tag 'asset_path' (Liquid::SyntaxError)
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:38:in `parse'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/tag.rb:10:in `parse'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/document.rb:5:in `parse'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:122:in `parse'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:108:in `parse'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:11:in `block in parse'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/liquid_renderer/file.rb:10:in `parse'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/convertible.rb:112:in `render_liquid'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/convertible.rb:215:in `render_all_layouts'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/convertible.rb:263:in `do_layout'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives/archive.rb:104:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:104:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:48:in `generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/site.rb:154:in `block in generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/site.rb:153:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/site.rb:153:in `generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/site.rb:58:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/command.rb:28:in `process_site'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:60:in `build'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:35:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `load'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `<main>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `eval'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `<main>'
```

As you can see, something in jekyll-archives appears to be causing this issue… following the error, it possibly relates to a definition where `to_liquid` is called (see [these lines](https://github.com/jekyll/jekyll-archives/blob/master/lib/jekyll-archives/archive.rb#L99-L105)). If I disable jekyll-archives, this plugin works fine.

I narrowed down the commit that started to throw this error: https://github.com/jekyll/jekyll-assets/commit/0796d2c187e1c223eb09220aa4f3ea7d7e764e20

Any clues why this conflict is now occurring? /cc @alfredxing

**Comment by paulrobertlloyd** [comment]
Thanks!

**Comment by alfredxing** [comment]
Hmm... as far as I can remember `jekyll-archives` doesn't use anything from Assets. Do you have the `asset_path` tag in one of your archive layouts?

**Comment by envygeeks** [comment]
@alfredxing somehow `Jekyll-Archives` is preventing our autoloads from working.  It never had this issue (as I don't use `jekyll-archives`) but it seems @paulrobertlloyd did as soon as he enabled it, at this point it's really a low-priority issue as the autoloads were reverted and a hot-fix issued already but it would be nice to know how this is happening.

**Comment by envygeeks** [comment]
We are no longer experiencing this problem since we don't autoload and probably won't in the near future. Closing this out, let me know if this is still a problem for you @paulrobertlloyd
