### ISSUE TITLE
jekyll 3.1.3 | Error:  undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by ChrisJefferson** [jekyll/jekyll-assets#283]
When I add jekyll-assets to my rep, I get the error of the title. This has come from taking a previous blog (which used jekyll-assets) and applying a new theme (jekyll-clean) to it. Not sure what I've done wrong. Any pointers welcome!

My repository can be seen at https://github.com/ChrisJefferson/jekyll-clean

The full error (with --verbose --trace) is given below.

```
 Rendering Layout: /page4/index.html
/usr/local/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.2.6/lib/jekyll/assets/env.rb:292:in `write_all': undefined method `map' for nil:NilClass (NoMethodError)
Did you mean?  tap
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.2.6/lib/jekyll/assets/hooks/jekyll/write.rb:9:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.1.3/lib/jekyll/hooks.rb:97:in `block in trigger'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.1.3/lib/jekyll/hooks.rb:96:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.1.3/lib/jekyll/hooks.rb:96:in `trigger'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.1.3/lib/jekyll/site.rb:204:in `write'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.1.3/lib/jekyll/site.rb:61:in `process'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.1.3/lib/jekyll/command.rb:26:in `process_site'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.1.3/lib/jekyll/commands/build.rb:60:in `build'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.1.3/lib/jekyll/commands/build.rb:33:in `process'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.1.3/lib/jekyll/commands/serve.rb:34:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.1.3/bin/jekyll:13:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by ChrisJefferson** [comment]
Update: I get this error if I just add jekyll-assets to a clean checkout of the jekyll-clean theme.

**Comment by envygeeks** [comment]
I thought I rid of this problem, I'll take a look with your repo and issue a hotfix if I can reproduce it.

**Comment by envygeeks** [comment]
I see what's happening, I don't even need to clone your repo to see the problem.  You have no assets at all yeah?  That's the problem, we assume at least one asset is being used but we really shouldn't.

**Comment by envygeeks** [comment]
@ChrisJefferson please try master and confirm it works for you, thanks.

**Comment by ChrisJefferson** [comment]
Yup, now works. Thanks.
