### ISSUE TITLE
Errno::EMFILE: Too many open files @ rb_sysopen

### ISSUE THREAD

**Issue by tonyarnold** [jekyll/jekyll-assets#339]
I've just tried to update from jekyll-assets 2.1.2 to 2.2.8, and I'm now getting the following error when starting Jekyll:

```
bundler: failed to load command: jekyll (/Users/tonyarnold/.rbenv/versions/2.3.0/bin/jekyll)
Errno::EMFILE: Too many open files @ rb_sysopen - /Users/tonyarnold/Documents/Itty Bitty Apps/revealapp.com/_assets/images/kb/integration/appcode/5-appcode@2x.jpg
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sprockets-3.6.3/lib/sprockets/asset.rb:99:in `binread'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sprockets-3.6.3/lib/sprockets/asset.rb:99:in `source'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sprockets-3.6.3/lib/sprockets/asset.rb:166:in `block in write_to'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sprockets-3.6.3/lib/sprockets/path_utils.rb:279:in `block in atomic_write'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sprockets-3.6.3/lib/sprockets/path_utils.rb:278:in `open'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sprockets-3.6.3/lib/sprockets/path_utils.rb:278:in `atomic_write'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sprockets-3.6.3/lib/sprockets/asset.rb:165:in `write_to'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.2.8/lib/jekyll/assets/manifest.rb:92:in `block (2 levels) in compile'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/ivar.rb:170:in `safe_execute'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/future.rb:52:in `block in execute'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
  /Users/tonyarnold/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

I've checked, and ulimit on this machine reports `unlimited`. Downgrading to 2.1.2 fixes the issue.

**Comment by envygeeks** [comment]
Even though we are inserted into the middle of this chain (because we forked Sprockets own Manifest) this bug probably lies within Sprockets or Concurrent Ruby (or both piggy backing a bug.) All of our stuff moves through Sprockets from Jekyll.  Please file this ticket upstream.

**Comment by tonyarnold** [comment]
Thanks. Which of the two projects would you suggest I file against?

**Comment by schristm** [comment]
+1

**Comment by tonyarnold** [comment]
@schristm FWIW executing `ulimit -n 8192` before running Jekyll works around the problem temporarily.

**Comment by schristm** [comment]
Thanks @tonyarnold. Is there an update on an actual fix?

**Comment by tonyarnold** [comment]
I couldn't figure out which project owned the issue, so I just dropped it. There's a workaround, and that's enough for what I needed to get done. Sorry!

**Comment by envygeeks** [comment]
This is a node bug technically, it's been happening for a lot of people on node, the only way to fix the problem is to increase your listeners on Linux so that it doesn't happen.
