### ISSUE TITLE
Magick not working at all

### ISSUE THREAD

**Issue by adrianjonmiller** [jekyll/jekyll-assets#366]
I've tried dozens of code examples and I cannot get the image magick to work at all.

Example of my markup
{% img "home_shot_1.jpg" magick:resize:1170x400 %}

**Comment by aaronwolen** [comment]
Is [mini_magick](https://github.com/minimagick/minimagick) installed?

**Comment by adrianjonmiller** [comment]
Yes, it is in the Gemfile and installed. I've run it without mini_magick in the gem file and it throws an error. That's the weird part: it sees that its installed and compiles without an error it just doesn't actually apply the transformations to the image.

**Comment by envygeeks** [comment]
Provide verbose or debug output please.

**Comment by streaps** [comment]
I think I have the same problem. No error with the build command, but I'm getting an error, if I update the page with jekyll-admin:

```
  Server running... press ctrl-c to stop.
                    undefined method `destroy!' for nil:NilClass
  Liquid Exception: undefined method `destroy!' for nil:NilClass in test.md
2017-04-17 17:40:50 - NoMethodError - undefined method `destroy!' for nil:NilClass:
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.2.8/lib/jekyll/assets/proxies/magick.rb:61:in `ensure in process'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.2.8/lib/jekyll/assets/proxies/magick.rb:61:in `process'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.2.8/lib/jekyll/assets/liquid/tag/proxied_asset.rb:103:in `block in proxy_file'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.2.8/lib/jekyll/assets/liquid/tag/proxied_asset.rb:102:in `each'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.2.8/lib/jekyll/assets/liquid/tag/proxied_asset.rb:102:in `proxy_file'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.2.8/lib/jekyll/assets/liquid/tag/proxied_asset.rb:33:in `initialize'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.2.8/lib/jekyll/assets/liquid/tag.rb:170:in `new'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.2.8/lib/jekyll/assets/liquid/tag.rb:170:in `find_asset'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.2.8/lib/jekyll/assets/liquid/tag.rb:97:in `render'
	/usr/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	/usr/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	/usr/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	/usr/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	/usr/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	/usr/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	/usr/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	/usr/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
	/usr/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
	/usr/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
	/usr/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
	/usr/lib/ruby/gems/2.3.0/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:40:in `measure_bytes'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:47:in `measure_time'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/renderer.rb:134:in `render_liquid'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/renderer.rb:82:in `run'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:463:in `block in render_pages'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:461:in `each'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:461:in `render_pages'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:191:in `render'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/site.rb:69:in `process'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-admin-0.4.1/lib/jekyll-admin/file_helper.rb:22:in `write_file'
	/usr/lib/ruby/gems/2.3.0/gems/jekyll-admin-0.4.1/lib/jekyll-admin/server/page.rb:22:in `block (2 levels) in <class:Server>'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/nulllogger.rb:9:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
	/usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/handler/webrick.rb:88:in `service'
	/usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by envygeeks** [comment]
Install imagemagick on your system.  Though this could also be related to the bugs I fixed tonight that involved the same thing, at this point I'm going to assume it's fixed, if it does not work with the release happening tonight or tomorrow please update the ticket and I'll happily look into it further.
