### ISSUE TITLE
jekyll 3.1.0 | Error undefined method 'gsub' for nil:NilClass in 

### ISSUE THREAD

**Issue by Stargator** [jekyll/jekyll-assets#368]
I am getting the following error due to trying to use the tags for individual css files as well as when I try using the tag for multiple assets. Am I using the tags incorrectly or is it something else?

I do have css files in _assets/css

Code that is causing the problem:
```html
    {% css base %}
    {% css skeleton %}
    {% css void %}
    {% css default %}
    {% css styles %}
```

As well as the following as a replacement:
```html
    {{ 'css:base.css css:skeleton.css css:void.css css:default.css css: css:styles.css' | jekyll_asset_multi }}
```

```bash
devops@Phoenix-Mobile:~/My-Repos/void-jekyll-theme$ bundle exec jekyll build --trace
Configuration file: My-Repos/void-jekyll-theme/_config.yml
            Source: .
       Destination: ./_site/
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Deprecation: You are using 'kramdown.coderay' in your configuration, please use 'syntax_highlighter_opts' instead.
  Liquid Exception: undefined method `gsub' for nil:NilClass in ./_layouts/base.html
My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-assets-2.2.8/lib/jekyll/assets/liquid/tag.rb:222:in `capture_and_out_error': undefined method `gsub' for nil:NilClass (NoMethodError)
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-assets-2.2.8/lib/jekyll/assets/liquid/tag.rb:102:in `rescue in render'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-assets-2.2.8/lib/jekyll/assets/liquid/tag.rb:91:in `render'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.6/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.6/lib/jekyll/liquid_renderer/file.rb:36:in `measure_bytes'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.6/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.6/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.6/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.6/lib/jekyll/renderer.rb:106:in `render_liquid'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.6/lib/jekyll/renderer.rb:146:in `place_in_layouts'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.6/lib/jekyll/renderer.rb:70:in `run'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.6/lib/jekyll/site.rb:179:in `block in render'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.6/lib/jekyll/site.rb:177:in `each'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.6/lib/jekyll/site.rb:177:in `render'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.6/lib/jekyll/site.rb:59:in `process'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.6/lib/jekyll/command.rb:26:in `process_site'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.6/lib/jekyll/commands/build.rb:60:in `build'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.6/lib/jekyll/commands/build.rb:33:in `process'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.6/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.6/bin/jekyll:13:in `<top (required)>'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/bin/jekyll:22:in `load'
	from My-Repos/void-jekyll-theme/vendor/bundle/ruby/2.3.0/bin/jekyll:22:in `<main>'
```

**Comment by envygeeks** [comment]
This seems to me to be an upstream usage bug.

**Comment by Stargator** [comment]
Upstream usage bug? What does that mean?
