### ISSUE TITLE
Problems with compressor?

### ISSUE THREAD

**Issue by AnatolZaitsev** [jekyll/jekyll-assets#385]
Everything was alright yesterday. Today I could't run jekyll with`jekyll serve`:

MacBook-Air:vx-promo Anatol_Zaitsev$ jekyll serve --trace
Configuration file: /Users/Anatol_Zaitsev/Documents/work/evrone/projects/vx-promo/_config.yml
            Source: /Users/Anatol_Zaitsev/Documents/work/evrone/projects/vx-promo
       Destination: /Users/Anatol_Zaitsev/Documents/work/evrone/projects/vx-promo/_site
      Generating... 
  Liquid Exception: undefined method `to_sym' for true:TrueClass Did you mean? to_s in _layouts/landing_redesign.html
/Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-assets-1.0.0/lib/jekyll/assets/configuration.rb:91:in `compressor': undefined method `to_sym' for true:TrueClass (NoMethodError)
Did you mean?  to_s
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-assets-1.0.0/lib/jekyll/assets/configuration.rb:50:in `js_compressor'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-assets-1.0.0/lib/jekyll/assets/environment.rb:31:in `initialize'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-assets-1.0.0/lib/jekyll/assets/patches/site_patch.rb:28:in `new'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-assets-1.0.0/lib/jekyll/assets/patches/site_patch.rb:28:in `assets'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-assets-1.0.0/lib/jekyll/assets/renderer.rb:39:in `asset'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-assets-1.0.0/lib/jekyll/assets/renderer.rb:73:in `render_tag'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-assets-1.0.0/lib/jekyll/assets/renderer.rb:57:in `render_stylesheet'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-assets-1.0.0/lib/jekyll/assets/tag.rb:11:in `render'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `each'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `render_all'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/liquid-2.6.2/lib/liquid/block.rb:82:in `render'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/liquid-2.6.2/lib/liquid/template.rb:128:in `render'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/liquid-2.6.2/lib/liquid/template.rb:138:in `render!'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:106:in `render_liquid'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:205:in `render_all_layouts'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:239:in `do_layout'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/page.rb:122:in `render'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:298:in `block in render'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `each'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `render'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/bin/jekyll:23:in `load'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/bin/jekyll:23:in `<main>'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/Anatol_Zaitsev/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by AnatolZaitsev** [comment]
some changes in _config.yml solve the error
