### ISSUE TITLE
Unknown tag 'asset_path' on master

### ISSUE THREAD

**Issue by migueldemoura** [jekyll/jekyll-assets#429]
After changing my Gem file from:
`gem 'jekyll-assets'`
to
`gem 'jekyll-assets', :git => 'https://github.com/jekyll/jekyll-assets.git'`

and installing the new version, I get this when trying to build the project:

`bundle exec jekyll build --trace`
```
Liquid Exception: Liquid syntax error (/home/user/folder_includes/image.html line 1): Unknown tag 'asset_path' included in /home/user/folder/_posts/post.md
/var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/document.rb:23:in `unknown_tag': Liquid syntax error (/home/user/folder/_includes/image.html line 1): Unknown tag 'asset_path' included  (Liquid::SyntaxError)
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/document.rb:11:in `block in parse'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:33:in `parse'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/document.rb:10:in `parse'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/document.rb:5:in `parse'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:132:in `parse'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:116:in `parse'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:12:in `parse'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/tags/include.rb:168:in `load_cached_partial'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/tags/include.rb:134:in `render'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:123:in `render_liquid'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:76:in `render_document'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:62:in `run'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:455:in `block (2 levels) in render_docs'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:453:in `each'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:453:in `block in render_docs'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:452:in `each_value'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:452:in `render_docs'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:192:in `render'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:73:in `process'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/command.rb:28:in `process_site'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:65:in `build'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:36:in `process'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/exe/jekyll:15:in `<top (required)>'
        from /usr/local/bin/jekyll:22:in `load'
        from /usr/local/bin/jekyll:22:in `<main>'
```

image.html
``` html
<a href="{% asset_path '{{ include.path }}' %}" data-something="...">
    <img src="{% asset_path '{{ include.path }}' %}">
</a>
```

post.md (relevant part)
```
{% include image.html path="image.png" %}
```

OS: Ubuntu 17.10
Jekyll: 3.6.2
Jekyll-Assets: current master - https://github.com/jekyll/jekyll-assets/commit/c2616b8625c500176225eb26447eeaad519566f3

**Comment by envygeeks** [comment]
We do not support `{% asset_path %}` anymore. https://github.com/jekyll/jekyll-assets#tag

**Comment by envygeeks** [comment]
You can do

```liquid
{% asset img.png @path %}
```

**Comment by envygeeks** [comment]
But really you should do

```liquid
<a href="{% asset_path '{{ include.path }}' %}" data-something="...">
    {% asset "{{ include.path }}" %}
</a>
```

We recently increased the scope of the context we give you from our Liquid processing.  So if that's inside of your `---` then it should work, if it's inside of your `_config.yml` it should work, if it's set inside of a Hook (that's done on `:pre_render`) it should also work!

**Comment by migueldemoura** [comment]
Appreciate the quick response!

I started using `asset_path` mainly for script and link tags, to avoid the extra attributes that are added via jekyll-assets, namely `type="text/javascript"` and `type="text/css"`, which are unnecessary for HTML5. Any plans on dropping them?

I'll be testing these new changes now, the "responsive" images are well worth using the alpha.

**Comment by envygeeks** [comment]
You should be able to do `{% asset my.js !type %}` and have no type.  While this was unintentional, it's a side affect of our extensible HTML defaults that `deep_merge` our values into yours, so if you set it to false, not only will our default not show up, but our HTML attribute builder will skip over it because it's false, and HTML doesn't support false attributes.

**Comment by migueldemoura** [comment]
Thanks for the feedback, just added the unset.

Still trying to debug it, but using {% asset file.js %} throws a `Liquid Exception: unknown keyword: hash in myfile`.

```
/var/lib/gems/2.3.0/gems/liquid-tag-parser-1.7.0/lib/liquid/tag/parser.rb:80:in `to_html': unknown keyword: hash (ArgumentError)
        from /home/user/.bundle/ruby/2.3.0/jekyll-assets-c2616b8625c5/lib/jekyll/assets/plugins/html/js.rb:17:in `block in run'
```

**Comment by envygeeks** [comment]
Update Jekyll-Assets

**Comment by migueldemoura** [comment]
Latest commit fixed that one.

Sorry to bug you with this, but still having another issue:

When using `{% asset '{{ include.path }}' %}`, with a valid path, the following error is thrown:

```
Liquid Exception: couldn't find file '' Checked in thesepaths: (...)
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/resolve.rb:65:in `resolve!': couldn't find file '' (Sprockets::FileNotFound)
```

Is the var not being handled?

**Comment by envygeeks** [comment]
Probably not because Jekyll treats context like garbage, so if we can't easily extract it in an obvious way we don't bother, and move on a case by case basis. File a ticket and I'll decide if it's worth it later, for now you can work around that problem with `{{ include.page | asset }}`.

**Comment by migueldemoura** [comment]
The workaround also throws an exception:

```
Liquid Exception: uninitialized constant Jekyll::Assets::Filters::Context in /home/user/_posts/post.md
/home/user/.bundle/ruby/2.3.0/jekyll-assets-e8a8ba847e49/lib/jekyll/assets/filters.rb:12:in `asset': uninitialized constant Jekyll::Assets::Filters::Context (NameError)
```

Will open a new issue for this.

**Comment by migueldemoura** [comment]
@envygeeks, just checked that the [suggested way of removing attributes from the assets](https://github.com/jekyll/jekyll-assets/issues/429#issuecomment-341943178) doesn't seem to work.

When using `{% asset main.js !type %}` I get:

``` html
<script src="/assets/main-digest.js" integrity="something" type="text/javascript"></script>
```

**Comment by mssun** [comment]
What if my asset is a file other than img, js, css?

For example, I use `asset_path` to get a PDF file before. What's the alternative for the `asset_.path` tag? I tried `{% asset xxx.pdf %}`, it doesn't work.

**Comment by envygeeks** [comment]
We never supported PDF's, but the documentation mentions how to get the path of an asset.

**Comment by mssun** [comment]
@envygeeks Yes, I know. Can you tell me how to get the path of an asset. I did not find the details in the readme. (maybe due to my careless)
