### ISSUE TITLE
Asset with multiple srcsets fails

### ISSUE THREAD

**Issue by migueldemoura** [jekyll/jekyll-assets#431]
Using the tag `asset` with multiple srcsets fails.

Example:
```
{% asset src
    srcset='magick:format=image/png magick:resize=400 media="(min-width:400px)"'
    srcset='magick:format=image/png magick:resize=600 media="(min-width:600px)"'
%}
```

Exception:
```
Liquid Exception: same file: /home/user/.jekyll-cache/assets/proxied/565191.png and /home/user/.jekyll-cache/assets/proxied/565191.png in /home/user/_posts/post.md
/usr/lib/ruby/2.3.0/fileutils.rb:1570:in `block in fu_each_src_dest': same file: /home/user/.jekyll-cache/assets/proxied/565191.png and /home/user/.jekyll-cache/assets/proxied/565191.png (ArgumentError)
```

OS: Ubuntu 17.10
Jekyll: 3.6.2
Jekyll-Assets: current master - https://github.com/jekyll/jekyll-assets/commit/e8a8ba847e49a98f0b7c3b04c0f5b7ec05bccdb3

**Comment by envygeeks** [comment]
That function is tested on Ubuntu 16.04 (Travis-CI,) Ubuntu 17.10 (my machine,) and Ubuntu 17.04. And specs are not failing at this time for that particular test.  Make sure you have imagemagick, librsvg-bin, and other necessary libraries for altering svg, or other images... as stated in the documentation.

If this is not the case, you will need to provide a proper trace with `--trace` and some debug logs.

**Comment by migueldemoura** [comment]
I have `gem 'mini_magick'` installed, as well as imagemagick.

Without the `magick:format=image/png`, there's no issue:
```
{% asset src
    srcset='magick:resize=400 media="(min-width:400px)"'
    srcset='magick:resize=600 media="(min-width:600px)"'
%}
```

Full stack trace:

```
Liquid Exception: same file: /home/user/.jekyll-cache/assets/proxied/565191.png and /home/user/.jekyll-cache/assets/proxied/565191.png in /home/user/_posts/2017-10-25-test.md
/usr/lib/ruby/2.3.0/fileutils.rb:1570:in `block in fu_each_src_dest': same file: /home/user/.jekyll-cache/assets/proxied/565191.png and /home/user/.jekyll-cache/assets/proxied/565191.png (ArgumentError)
        from /usr/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
        from /usr/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
        from /usr/lib/ruby/2.3.0/fileutils.rb:402:in `cp'
        from /home/user/.bundle/ruby/2.3.0/jekyll-assets-4db146d24ddc/lib/jekyll/assets/plugins/proxy/magick.rb:50:in `magick_format'
        from /home/user/.bundle/ruby/2.3.0/jekyll-assets-4db146d24ddc/lib/jekyll/assets/plugins/proxy/magick.rb:22:in `process'
        from /home/user/.bundle/ruby/2.3.0/jekyll-assets-4db146d24ddc/lib/jekyll/assets/proxy.rb:49:in `block (2 levels) in proxy'
        from /home/user/.bundle/ruby/2.3.0/jekyll-assets-4db146d24ddc/lib/jekyll/assets/proxy.rb:42:in `each'
        from /home/user/.bundle/ruby/2.3.0/jekyll-assets-4db146d24ddc/lib/jekyll/assets/proxy.rb:42:in `block in proxy'
        from /var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cache.rb:85:in `fetch'
        from /home/user/.bundle/ruby/2.3.0/jekyll-assets-4db146d24ddc/lib/jekyll/assets/proxy.rb:41:in `proxy'
        from /home/user/.bundle/ruby/2.3.0/jekyll-assets-4db146d24ddc/lib/jekyll/assets/tag.rb:49:in `render'
        from /home/user/.bundle/ruby/2.3.0/jekyll-assets-4db146d24ddc/lib/jekyll/assets/plugins/html/pic.rb:30:in `block (3 levels) in run'
        from /home/user/.bundle/ruby/2.3.0/jekyll-assets-4db146d24ddc/lib/jekyll/assets/plugins/html/pic.rb:28:in `each'
        from /home/user/.bundle/ruby/2.3.0/jekyll-assets-4db146d24ddc/lib/jekyll/assets/plugins/html/pic.rb:28:in `block (2 levels) in run'
        from /var/lib/gems/2.3.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/builder.rb:391:in `insert'
        from /var/lib/gems/2.3.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/builder.rb:375:in `method_missing'
        from /home/user/.bundle/ruby/2.3.0/jekyll-assets-4db146d24ddc/lib/jekyll/assets/plugins/html/pic.rb:26:in `block in run'
        from /var/lib/gems/2.3.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/builder.rb:293:in `initialize'
        from /var/lib/gems/2.3.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/builder.rb:254:in `new'
        from /var/lib/gems/2.3.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/builder.rb:254:in `with'
        from /home/user/.bundle/ruby/2.3.0/jekyll-assets-4db146d24ddc/lib/jekyll/assets/plugins/html/pic.rb:25:in `run'
        from /home/user/.bundle/ruby/2.3.0/jekyll-assets-4db146d24ddc/lib/jekyll/assets/html.rb:45:in `block in build'
        from /home/user/.bundle/ruby/2.3.0/jekyll-assets-4db146d24ddc/lib/jekyll/assets/html.rb:37:in `each'
        from /home/user/.bundle/ruby/2.3.0/jekyll-assets-4db146d24ddc/lib/jekyll/assets/html.rb:37:in `build'
        from /home/user/.bundle/ruby/2.3.0/jekyll-assets-4db146d24ddc/lib/jekyll/assets/tag.rb:58:in `render'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
        from /var/lib/gems/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:123:in `render_liquid'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:76:in `render_document'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:62:in `run'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:455:in `block (2 levels) in render_docs'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:453:in `each'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:453:in `block in render_docs'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:452:in `each_value'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:452:in `render_docs'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:192:in `render'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:73:in `process'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/command.rb:28:in `process_site'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:65:in `build'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:36:in `process'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `block (3 levels) in init_with_program'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `each'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `block (2 levels) in init_with_program'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/exe/jekyll:15:in `<top (required)>'
        from /usr/local/bin/jekyll:22:in `load'
        from /usr/local/bin/jekyll:22:in `<main>'
```

**Comment by migueldemoura** [comment]
Found the issue, trying to convert to the same extension obviously throws that error since they use the same dir for input and output. Closed.

**Comment by envygeeks** [comment]
We should probably detect that.
