### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by migueldemoura** [jekyll/jekyll-assets#437]
```
Configuration file: /something/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-assets or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-assets' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
jekyll 3.6.2 | Error:  jekyll-assets
```

Gemfile
```
gem 'autoprefixer-rails'
gem 'html-proofer'
gem 'image_optim'
gem 'jekyll-assets', :git => 'https://github.com/jekyll/jekyll-assets.git'
gem 'jekyll-paginate-v2'
gem 'jekyll-sitemap'
gem 'jekyll'
gem 'jemoji'
gem 'mini_magick'
gem 'sass'
gem 'uglifier'
```

_config.yml (partial)
``` yaml
plugins:
  - jekyll-assets
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jemoji
```

This was introduced on https://github.com/jekyll/jekyll-assets/commit/dfe453d8a927a50ba1ca45a6602eab5669d02efd, reverting it fixes the issue.

OS: Ubuntu 17.10
Jekyll: 3.6.2
Jekyll-Assets: current master

**Comment by envygeeks** [comment]
We no longer support `jekyll-assets.rb`, add Jekyll Assets to your Jekyll Plugins group.  Unfortunately we are moving forward with this library and jekyll-assets.rb triggers linting errors (one that for once I agree with.)

**Comment by migueldemoura** [comment]
Thanks, just changed all plugins to that method!

**Comment by illycz** [comment]
I don't understand what I need to change?
Same error.

Gemfile:
```
group :jekyll_plugins do
  gem "autoprefixer-rails"
  gem "jekyll-assets", "~> 3.0.0"
  gem "jekyll-feed", "~> 0.6"
end
```

_config.yml:
```
plugins:
  - autoprefixer-rails
  - jekyll-assets
  - jekyll-feed

assets:
  autoprefixer:
    browsers:
      - "> 1%"
      - "last 2 versions"
```

Thanks

**Comment by envygeeks** [comment]
Don't ad it to your plugins list, Jekyll will try to require "jekyll-assets.rb".

**Comment by illycz** [comment]
When I remove it,  i get this:

```
Liquid Exception: Liquid syntax error (.../_includes/head.html line 10): Unknown tag 'css' included in /_layouts/default.html
```

In head.html:
```
{% css main %}
```

I can't implement jekyll-assets to basic jekyll installation :(

**Comment by envygeeks** [comment]
Update your source, we don't support any tag but asset, the documentation has instructions: https://github.com/envygeeks/jekyll-assets#usage-1

**Comment by illycz** [comment]
Thanks, another:
```
Liquid Exception: "\xE6" on US-ASCII in /_layouts/default.html
```

Thanks for your patience :)

**Comment by illycz** [comment]
I removed everything except `{% asset main !type %}` in default.html.
In index.md I have only:
```
---
layout: default
---
```

When I remove `{% asset main !type %}` everything working...
And still same error. I'm desperate...

**Comment by envygeeks** [comment]
Run with `--trace` and file a uniq bug, instead of necromancing please.

**Comment by illycz** [comment]
```
Generating...
  Liquid Exception: "\xE6" on US-ASCII in /_layouts/default.html
/Users/illy/.rvm/gems/ruby-2.3.4/gems/execjs-2.7.0/lib/execjs/encoding.rb:22:in `encode': "\xE6" on US-ASCII (Encoding::InvalidByteSequenceError)
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/execjs-2.7.0/lib/execjs/encoding.rb:22:in `encode'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:8:in `initialize'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `new'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `compile'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/execjs-2.7.0/lib/execjs/module.rb:27:in `compile'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/autoprefixer-rails-6.7.7.2/lib/autoprefixer-rails/processor.rb:131:in `runtime'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/autoprefixer-rails-6.7.7.2/lib/autoprefixer-rails/processor.rb:30:in `process'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/autoprefixer-rails-6.7.7.2/lib/autoprefixer-rails/sprockets.rb:20:in `run'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/autoprefixer-rails-6.7.7.2/lib/autoprefixer-rails/sprockets.rb:14:in `call'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-assets-3.0.0/lib/jekyll/assets/patches/cached_env.rb:53:in `find_asset!'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-assets-3.0.0/lib/jekyll/assets/patches/cached_env.rb:65:in `find_asset!'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-assets-3.0.0/lib/jekyll/assets/tag.rb:159:in `internal'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-assets-3.0.0/lib/jekyll/assets/tag.rb:57:in `render_raw'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-assets-3.0.0/lib/jekyll/assets/tag.rb:72:in `render'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/tags/include.rb:139:in `block in render'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/liquid-4.0.0/lib/liquid/context.rb:123:in `stack'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/tags/include.rb:136:in `render'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:123:in `render_liquid'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:188:in `render_layout'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:155:in `place_in_layouts'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:85:in `render_document'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:62:in `run'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/site.rb:455:in `block (2 levels) in render_docs'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/site.rb:453:in `each'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/site.rb:453:in `block in render_docs'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/site.rb:452:in `each_value'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/site.rb:452:in `render_docs'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/site.rb:192:in `render'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/site.rb:73:in `process'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/command.rb:28:in `process_site'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:65:in `build'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:36:in `process'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `block (3 levels) in init_with_program'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `each'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `block (2 levels) in init_with_program'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /Users/illy/.rvm/gems/ruby-2.3.4/gems/jekyll-3.6.2/exe/jekyll:15:in `<top (required)>'
        from /Users/illy/.rvm/gems/ruby-2.3.4/bin/jekyll:23:in `load'
        from /Users/illy/.rvm/gems/ruby-2.3.4/bin/jekyll:23:in `<main>'
        from /Users/illy/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
        from /Users/illy/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by illycz** [comment]
Any idea? Thanks...

**Comment by illycz** [comment]
Maybe same problem like here? https://github.com/babel/ruby-babel-transpiler/issues/294

**Comment by illycz** [comment]
Resolved by changing encoding: https://stackoverflow.com/questions/17031651/invalid-byte-sequence-in-us-ascii-argument-error-when-i-run-rake-dbseed-in-ra

Thanks for your time
